### ISSUE TITLE
TypeError: Cannot read property 'sequelize' of undefined with Sequelize version 3.1

### ISSUE THREAD

**Issue by Yamilquery** [overlookmotel/sequelize-hierarchy#13]
Hi, i get this error:

TypeError: Cannot read property 'sequelize' of undefined

This happen when i add the hierarchy attribute:
parent_id:{type: DataTypes.INTEGER, hierarchy: true }

I hope can help me please.

**Comment by overlookmotel** [comment]
I'm afraid only Sequelize v2.x.x is supported at present.

I'm going to provide support for v3, but don't have time to do it at the moment.

However, I see that @ipelovski and @Yizen have both forked sequelize-hierarchy in order to get it working with v3. Maybe you can try one of their forks:
https://github.com/ipelovski/sequelize-hierarchy
https://github.com/Yizen/sequelize-hierarchy

@ipelovski and @Yizen: are your forks working with v3? Do either of you want to submit a PR?

**Comment by Yizen** [comment]
Hi, my fork is working with v3, but has been tested for far only for mySQL. @ipelovski branch has been tested under Postgresql.

I can submit a PR, but this will break the Sequelize v2 compatibility...

**Comment by ipelovski** [comment]
Hi, the changes in my fork are not backward compatible with v2. Also I can only test for sqlite and postgres.

**Comment by overlookmotel** [comment]
@Yizen and @ipelovski: thanks for your swift replies.

Ah OK, yes, it would be good to maintain back-compatibility with Sequelize v2. I'll have a look at the changes you've made to make it work for v3 and see if I can add them in while maintaining backward-compatibility...

**Comment by overlookmotel** [comment]
Actually, I had some time, so did some work on this.

Version 0.3.0, just released, supports both Sequelize v2 and v3.

Thanks @Yizen and @ipelovski for your work on this - made it much easier to do.

@Yamilquery Hopefully this solves your issue. Can you please let me know if it does?

**Comment by Yizen** [comment]
Thanks a lot @overlookmotel : I switched my app back from my fork to your master, and it's working perfectly (mysql, sequelize v3).
