### ISSUE TITLE
table ancestors doesn't exist

### ISSUE THREAD

**Issue by heryvandoro** [overlookmotel/sequelize-hierarchy#148]
Here is my table structure : 
id
parent_id
name
hierarchy_level

**model :** 
const Category = conn.sequelize.define('category', {
    id:
    {
        type: Sequelize.INTEGER,
        primaryKey: true,
        autoIncrement: true,
    },
    parent_id : {
        type : Sequelize.INTEGER,
    },
    name : Sequelize.STRING,
},{
    underscored: true,
    timestamps: false,
    freezeTableName: true,
});

Category.isHierarchy()
module.exports = Category;

**controller :** 
get(id, params)
    {
    	return Model.findOne({
            where : {
                id: id
            },
            include: {
                model: Model,
                as: 'descendents',
                hierarchy: true
            }
        }).then(category => {
    		return Promise.resolve({
                data: category
            });
        });
    },

When i try to fetch all data with it's children, it's worked. But it wasn't work when fetching one data with `findOne({ where : {  id : id } })`. Whats wrong? 
Here is error messages : 
`SequelizeDatabaseError: Table 'db.categoriesancestors' doesn't exist`

**Comment by heryvandoro** [comment]
Fixed, i'm forgot to override ancestors model 👍

**Comment by overlookmotel** [comment]
Glad you figured it out!

**Comment by gusev-genotek** [comment]
> Fixed, i'm forgot to override ancestors model

Hey, what do you mean by "override ancestors model". Would appreciate an example.

Thanks

**Comment by qunaxis** [comment]
> > Fixed, i'm forgot to override ancestors model
> 
> Hey, what do you mean by "override ancestors model". Would appreciate an example.
> 
> Thanks

+1. I have the same issue.

**Comment by qunaxis** [comment]
> > > Fixed, i'm forgot to override ancestors model
> > 
> > 
> > Hey, what do you mean by "override ancestors model". Would appreciate an example.
> > Thanks
> 
> +1. I have the same issue.

I figured it out.

@gusev-genotek, "Override ancestors model" means synchronize ancestors model (or models — in my case there are several) with the database through function `.sync`. The `force: true` parameter does not matter because the ancestor model does not change after initialization (in the usual case). 
P.S. Отпишись, если пригодилось.

@overlookmotel, thank you for the convenient and useful package!

**Comment by gusev-genotek** [comment]
Thanks. I don't have ancestor models. Documentation never mentions ancestor models. I thought the only thing one had to do to use this plugin is to add hierarchy:true to an existing model, which would create all necessary models behind the scenes.

In order to fix this I had to manually create a ancestor's sql table with foreign keys pointing to my model.

**Comment by overlookmotel** [comment]
This library creates the ancestors model, but that doesn't create the table in database, unless you use `.sync()`. This is the same as with when creating any model with Sequelize.

But anyway, I've added a clearer explanation to the README.
