### ISSUE TITLE
treeverse mention in readme

### ISSUE THREAD

**Issue by ianengelbrecht** [overlookmotel/sequelize-hierarchy#189]
Perhaps worth dropping a mention for [treeverse](https://www.npmjs.com/package/treeverse) in the README. Looks like it might play nicely with this library.

**Comment by overlookmotel** [comment]
Thanks for suggestion. However, I'm afraid I don't have time to research this module, and don't want to endorse it without knowing it well and knowing it works, otherwise it's not very helpful to users!

Also, I notice it only has ~20 weekly NPM downloads so it doesn't look like it's much used - no way to say if it will remain maintained.

Ergh sorry if this seems rude. I don't mean to be. Just little time to deal with the urgent things even.
