### ISSUE TITLE
bug: It allows "invalid" tree states

### ISSUE THREAD

**Issue by diosney** [overlookmotel/sequelize-hierarchy#23]
Hi,

I created several objects with different tree configurations and found out that the plugin is permissive on some somewhat invalid or not common configurations. For example, it allows:

* setting `parent_id` to itself.

* setting `parent_id` of a root to the child id, creating a cycle.

**Comment by overlookmotel** [comment]
Hi @diosney.

Could you possibly post some code that creates these illegal states?

The code should be checking for illegal states (trying to make a object the parent of itself etc) and throwing an error - so this sounds like a bug. I'd like to fix it but a solid example would be very helpful.

**Comment by overlookmotel** [comment]
Ping @diosney

**Comment by overlookmotel** [comment]
Ping @diosney

**Comment by faceleg** [comment]
I'm interested to see this also

**Comment by overlookmotel** [comment]
@diosney Are you able to post some more details on this? I'm keen to track down the bugs if they are there.

**Comment by overlookmotel** [comment]
Hi @diosney. Dude, why do you open an issue and then not provide enough details for me to fix it?! Wake up!

**Comment by diosney** [comment]
@overlookmotel Hahaha! Sorry for the delay. 

Please, understand that we have different personal/professional situations that directly affect our time and how we use it, so excuse me if I couldn't get to you in the proper time according with your standards (and thanks you for not closing the issue but asking for more data).

About the issues I encountered, they can be easily reproduced, just create a hierarchical model (I do it with `hierarchy: true` at the model definition), and then do the following steps for each "bug":

* ISSUE 1: plugin allows setting `parent_id` to itself:
       * create an object from the hierarchical model with no `parent_id`, let it be instance A.
       * create a child object of instance A by setting its `parent_id` to the `id` of instance A.
       * then update the **child** object `parent_id` property to be the `id` of the **child** object.

* ISSUE 2: plugin allows to create cyclic trees:
     * create an object from the hierarchical model with no `parent_id`, let it be instance A.
     * create a child object of instance A by setting its `parent_id` to the `id` of instance A.
     * then update the **parent** object `parent_id` property to be the `id` of the **child** object.

Those issues should be considered bugs unless you specifically state that are *features*.

I tested that against `^0.5.7`.

Thanks

**Comment by overlookmotel** [comment]
Really sorry, after being so demanding that you answer, I didn't do anything about this issue for 8 months!

But it's fixed in v0.7.0. An error is thrown if you try to either `create` or `updateAttributes` creating an item which is it's own parent.

I couldn't reproduce your "case 2" though. There's been a test in place since already before v0.5.7 for trying to update an item to make it a child of one of it's descendents. That test (https://github.com/overlookmotel/sequelize-hierarchy/blob/master/test/all.test.js#L366) appears to be an exact reproduction of your "case 2".

Closing this issue, but if you find that it's still possible to create an illegal state, please re-open or comment.

Thanks loads for bringing this to my attention and, again, sorry for my earlier rudeness and for taking so long to fix this.
