### ISSUE TITLE
Retrieving hierarchy with where clause

### ISSUE THREAD

**Issue by nareynolds** [overlookmotel/sequelize-hierarchy#44]
Hi,

I've created a hierarchical "Location" model, which has a boolean "active" property. I'd like to be able to query for the hierarchy where "active = true", so that any inactive Locations and their sub-hierarchies are not retrieved. However, when I do (as shown below) so I receive the following error: "SequelizeHierarchyError: Parent ID 1 not found in result set."

```
        Location.findAll({
            where: { active: true },
            hierarchy: true,
            order: [['name']]
        })
```

Is there a way achieve this?

**Comment by overlookmotel** [comment]
Hmm. This is a tricky one.

I think the reason for the error is that a location (with Id = 1) has been marked as inactive and so is not fetched, but one/some of the children of that location (with ParentId = 1) are active and so are fetched. Then when it tries to create the nested hierarchy, it can't find the parent in the result set, and so throws an error.

The only way to avoid this problem is to ensure that when a location is made inactive, all its descendants are also made inactive.

Sorry that's a pain, but it's the only way to do it at present, and I can't see any nice way to change the plugin to support an easier method. Unless you can think of one?

**Comment by nareynolds** [comment]
Thanks. In the end I had to make 2 queries:
1) to find all the inactive Locations including its descendents in a flat array. Then I extract all the IDs.
```
        return Location.findAll({
            include: { model: Location, as: 'descendents', hierarchy: false },
            where: { active: false}
        })
            .then(function (locations) {
                // gather all their IDs
                var ids = _.pluck(locations, 'id');
                _.forEach(locations, function (location) {
                    if (location.descendents && location.descendents.length) {
                        ids = ids.concat(_.pluck(location.descendents, 'id'));
                    }
                });
                return ids;
            })
```

2) get hierarchy where Location IDs are NOT IN the extracted list above
```
                    return Location.findAll({
                        where: { id: { $notIn: ids} },
                        hierarchy: true,
                        order: [['name']]
                    })
                        .then(function (locations) {
                            // whatever...
                        });
```
