### ISSUE TITLE
support for custom column names

### ISSUE THREAD

**Issue by php-workx** [overlookmotel/sequelize-hierarchy#70]
Unfortunately `sequelize-hierarchy` does not respect settings for custom field names. This can be replicate by simply changing the folder model definition in the default test suite to something like that:

```
id: {
  type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true,
  field: 'folder_id',
}
```

The result will be an error: `SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'IN/ALL/ANY subquery'`

Caused by this query:
```
UPDATE `tFolder` SET `hierarchy_level` = `hierarchy_level` + -2 WHERE `id` IN ( SELECT `folder_id` FROM `tFolderAncestors` AS ancestors WHERE ancestors.`ancestor_id` = 104)
```

This is a pretty serious issue cause it affects everybody who is not using default column names.

**Comment by php-workx** [comment]
BTW: I can try work on a PR if you give me an idea where to look at.

**Comment by overlookmotel** [comment]
I *think* this is fixed in v0.7.5 (just released). Can you please test it out and let me know?

NB The `primaryKey`, `foreignKey`, `throughKey`, `throughForeignKey` and `levelFieldName` options should contain the *model* field name, NOT the *table* field name. i.e. in your case `options.primaryKey = 'id'` (the default).

In truth, there should be more tests for this module, which would have caught issues like this - but I don't have time to write them!

**Comment by overlookmotel** [comment]
@php-workx Can you please confirm whether v0.7.5 solved this issue for you?

**Comment by php-workx** [comment]
looks good to me. thx!
